# Generated by Django 5.1.4 on 2025-01-12 18:28

import utils.file_uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_user_options_alter_user_profile_photo_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='static/images/posts/default.jpg', upload_to=utils.file_uploader.uploaded_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='static/images/users/default.png', upload_to=utils.file_uploader.uploaded_file_path, verbose_name='Фото профиля'),
        ),
    ]
