# Generated by Django 5.1.4 on 2025-01-13 12:19

from django.db import migrations, models

import utils.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts/default.jpg', upload_to=utils.file_uploader.uploaded_file_path, verbose_name='Изображение'),
        ),
    ]
