# Generated by Django 5.1.4 on 2025-01-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_post_votes_number_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_number',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество комментариев'),
        ),
    ]
