# Generated by Django 5.1.6 on 2025-03-04 13:16

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_post_comments_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=django_fsm.FSMField(choices=[('PENDING', 'На модерации'), ('APPROVED', 'Одобрен'), ('REJECTED', 'Отклонен')], default='PENDING', max_length=50, protected=True, verbose_name='Статус'),
        ),
    ]
