# Generated by Django 5.1.6 on 2025-03-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_post_comments_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Статус', choices=[
                ('PENDING', 'На модерации'),
                ('APPROVED', 'Одобрен'),
                ('REJECTED', 'Отклонен')
            ], default='PENDING'),
        ),
    ]
