# Generated by Django 5.1.7 on 2025-03-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ONDELETE', 'On delete')], default='PENDING', max_length=50, verbose_name='Статус'),
        ),
    ]
