# Generated by Django 5.1.7 on 2025-03-22 16:16

import utils.file_uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_rename_status_post_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=utils.file_uploader.uploaded_file_path, verbose_name='Фото профиля'),
        ),
    ]
