# Generated by Django 5.1.7 on 2025-03-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='state',
        ),
    ]
